version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: GO111MODULE=on go build main.go
  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: echo hello
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
